all:
	javac ./src/*.java
run:
	java -classpath src PlayGame Classical
run1:
	java -classpath src PlayGame VarianceOne
run2:
	java -classpath src PlayGame VarianceTwo
run3:
	java -classpath src PlayGame VarianceThree
test:
	java -classpath src test


